apiVersion: operator.openshift.io/v1
kind: Console
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: '2'
  name: cluster
spec:
  plugins:
    - monitoring-plugin
    - odf-console
    - gitops-plugin
    - logging-view-plugin
    - netobserv-plugin
