apiVersion: v1
kind: Namespace
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: '-1'
  name: openshift-logging
  labels:
    openshift.io/cluster-monitoring: "true"
    openshift.io/cluster-logging: "true"
