kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: flowcollectors.flows.netobserv.io-v1beta2-admin-openshift-gitops-argocd-application-controller
  annotations:
    argocd.argoproj.io/sync-wave: '1'
subjects:
  - kind: ServiceAccount
    name: openshift-gitops-argocd-application-controller
    namespace: openshift-gitops
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: flowcollectors.flows.netobserv.io-v1beta2-admin
