apiVersion: v1
kind: Namespace
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: '-1'
    openshift.io/node-selector: "node-role.kubernetes.io/infra="
  name: openshift-storage
  labels:
    openshift.io/cluster-monitoring: "true"
