apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: odf-operator
  namespace: openshift-storage
spec:
  channel: "stable-4.16"
  config:
    nodeSelector:
      node-role.kubernetes.io/infra: ''
    tolerations:
      - key: node.ocs.openshift.io/storage
        operator: Equal
        value: "true"
  name: odf-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
