kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: '1'
  name: storageclusters.ocs.openshift.io-v1-admin-openshift-gitops-argocd-application-controller
  namespace: openshift-storage
subjects:
  - kind: ServiceAccount
    name: openshift-gitops-argocd-application-controller
    namespace: openshift-gitops
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: storageclusters.ocs.openshift.io-v1-admin
