apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: '1'
  name: odf-operator
  namespace: openshift-storage
spec:
  channel: "stable-4.16"
  config:
    nodeSelector:
      node-role.kubernetes.io/infra: ''
    tolerations:
      - key: node-role.kubernetes.io/infra
        operator: Exists
  name: odf-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
